/* UniAtlas — Projects & Volunteering resource list (reuses CAREER_DATA categories) */

const TYPE_LABELS = {
  project: { ru: 'Проект', en: 'Project', kz: 'Жоба' },
  olympiad: { ru: 'Олимпиада', en: 'Olympiad', kz: 'Олимпиада' },
  volunteering: { ru: 'Волонтёрство', en: 'Volunteering', kz: 'Еріктілер' },
  internship: { ru: 'Стажировка', en: 'Internship', kz: 'Тәжірибеден өту' },
};

const RESOURCES = [
  { id: 'r1', category: 'tech', type: 'olympiad', title: { ru: 'Хакатон или соревнование по программированию', en: 'Hackathon or coding competition', kz: 'Хакатон немесе бағдарламалау байқауы' }, desc: { ru: 'Участвуй в школьных или открытых хакатонах, выложи проекты на GitHub — это сильный пункт портфолио.', en: 'Join school or open hackathons and publish your projects on GitHub — a strong portfolio item.', kz: 'Мектеп немесе ашық хакатондарға қатыс, жобаларыңды GitHub-қа жүкте — бұл портфолионың мықты тармағы.' } },
  { id: 'r2', category: 'tech', type: 'project', title: { ru: 'Онлайн-курс + пет-проект', en: 'Online course + personal project', kz: 'Онлайн курс + жеке жоба' }, desc: { ru: 'Пройди курс на Coursera или edX и сделай на его основе свой мини-проект: сайт, приложение или бота.', en: 'Take a Coursera or edX course and build a small project from it: a website, app or bot.', kz: 'Coursera немесе edX курсынан өт және соның негізінде өз мини-жобаңды жаса: сайт, қосымша немесе бот.' } },
  { id: 'r3', category: 'science', type: 'olympiad', title: { ru: 'Школьная научно-исследовательская работа', en: 'School research project', kz: 'Мектеп ғылыми-зерттеу жұмысы' }, desc: { ru: 'Напиши исследовательскую работу и представь её на конференции НОУ или профильной олимпиаде.', en: 'Write a research paper and present it at a student research conference or subject olympiad.', kz: 'Зерттеу жұмысын жазып, оны ғылыми қоғам конференциясында немесе пәндік олимпиадада таныстыр.' } },
  { id: 'r4', category: 'science', type: 'project', title: { ru: 'Летняя школа при университете', en: 'University summer school', kz: 'Университеттің жазғы мектебі' }, desc: { ru: 'Найди летние STEM-программы при университетах — многие предлагают гранты на участие.', en: 'Look for STEM summer programs at universities — many offer participation grants.', kz: 'Университеттердің жазғы STEM бағдарламаларын тап — көбі қатысуға грант ұсынады.' } },
  { id: 'r5', category: 'creative', type: 'project', title: { ru: 'Личный творческий проект', en: 'A personal creative project', kz: 'Жеке шығармашылық жоба' }, desc: { ru: 'Веди блог, YouTube-канал, подкаст или серию иллюстраций — регулярность важнее масштаба.', en: 'Run a blog, YouTube channel, podcast or illustration series — consistency matters more than scale.', kz: 'Блог, YouTube арна, подкаст немесе иллюстрация сериясын жүргіз — тұрақтылық ауқымнан маңызды.' } },
  { id: 'r6', category: 'creative', type: 'olympiad', title: { ru: 'Конкурс дизайна или медиа', en: 'Design or media competition', kz: 'Дизайн немесе медиа байқауы' }, desc: { ru: 'Участвуй в конкурсах фотографии, дизайна или короткого видео — локальных и международных.', en: 'Enter photography, design or short-video competitions — local and international.', kz: 'Фотография, дизайн немесе қысқа видео байқауларына қатыс — жергілікті және халықаралық.' } },
  { id: 'r7', category: 'social', type: 'volunteering', title: { ru: 'Волонтёрство в местной НКО', en: 'Volunteering at a local NGO', kz: 'Жергілікті ҮЕҰ-да еріктілік' }, desc: { ru: 'Помогай приюту, экологической организации или благотворительному фонду в своём городе.', en: 'Help a shelter, environmental group or charity fund in your city.', kz: 'Қалаңдағы баспана, экологиялық ұйым немесе қайырымдылық қорына көмектес.' } },
  { id: 'r8', category: 'social', type: 'volunteering', title: { ru: 'Менторство и репетиторство', en: 'Mentoring and tutoring', kz: 'Менторлық және репетиторлық' }, desc: { ru: 'Помогай младшим ученикам с предметами — это показывает лидерство и заботу о других.', en: 'Help younger students with schoolwork — it shows leadership and care for others.', kz: 'Кіші сынып оқушыларына пәндер бойынша көмектес — бұл көшбасшылық пен қамқорлықты көрсетеді.' } },
  { id: 'r9', category: 'enterprising', type: 'project', title: { ru: 'Школьный стартап-проект', en: 'A student startup project', kz: 'Мектеп стартап жобасы' }, desc: { ru: 'Придумай мини-бизнес или социальный проект и участвуй в школьных бизнес-конкурсах.', en: 'Come up with a mini-business or social venture and enter student business competitions.', kz: 'Мини-бизнес немесе әлеуметтік жоба ойлап тауып, мектеп бизнес байқауларына қатыс.' } },
  { id: 'r10', category: 'enterprising', type: 'internship', title: { ru: 'Стажировка или шедоуинг', en: 'Internship or job shadowing', kz: 'Тәжірибеден өту немесе шедоуинг' }, desc: { ru: 'Договорись о короткой стажировке или дне наблюдения за работой в местной компании.', en: 'Arrange a short internship or a day shadowing someone at a local company.', kz: 'Жергілікті компанияда қысқа тәжірибеден өтуге немесе бір күн бақылауға келіс.' } },
  { id: 'r11', category: 'organizing', type: 'project', title: { ru: 'Организация школьного мероприятия', en: 'Organizing a school event', kz: 'Мектеп іс-шарасын ұйымдастыру' }, desc: { ru: 'Создай клуб, организуй ивент или дебат-команду — покажи навыки планирования.', en: 'Start a club, organize an event or a debate team — show your planning skills.', kz: 'Клуб құр, іс-шара немесе дебат командасын ұйымдастыр — жоспарлау дағдыларыңды көрсет.' } },
  { id: 'r12', category: 'organizing', type: 'volunteering', title: { ru: 'Ученическое самоуправление', en: 'Student government', kz: 'Оқушылардың өзін-өзі басқаруы' }, desc: { ru: 'Участвуй в школьном совете или старостате — координируй проекты и представляй интересы учеников.', en: 'Join student council or class leadership — coordinate projects and represent student interests.', kz: 'Мектеп кеңесіне немесе старосталыққа қатыс — жобаларды үйлестір, оқушылар мүддесін білдір.' } },
];
